### ISSUE TITLE
OpenAI access token needs to be enclosed in quotes

### ISSUE THREAD

**Issue by c-sonnier** [silva96/ai_stories#5]
I am unable to connect to OpenAI when I enter my token without enclosing in quotations:
i.e. `OPENAI_ACCESS_TOKEN=sk-randomcharacters` 

 I have no issues connecting to OpenAI if I enter my token enclosed with quotes:
 i.e. `OPENAI_ACCESS_TOKEN="sk-randomcharacters"`

**Comment by silva96** [comment]
That's curious, It should be all good but, doesn't hurt to add them. I could add it to the readm, thanks.
