### ISSUE TITLE
Use the new gpt-3.5-turbo model

### ISSUE THREAD

**Issue by silva96** [silva96/ai_stories#9]
We want to explore how are the stories generated using the new chatgpt api model 

Here's the documentation of the new model

https://platform.openai.com/docs/guides/chat

It should be as easy as changing the usage of the old endpoint for the new one and configure parameters properly.

But first we need to update the open ai gem.

We are using this gem:

https://github.com/alexrudall/ruby-openai

Otherwise you wont be able to use the new endpoint.

Please make sure you update every usage of the gem to the new endpoint. 

They are mostly used in the jobs (app/jobs directory)

Take as an example this:

```ruby
@client.completions(
      parameters: {
        model: 'text-davinci-003',
        prompt:, max_tokens: (DAVINCI_MAX_TOKENS - prompt.size)
      }
    )

```

That's using davinci 003

You need to update those calls to use gpt3.5-turbo

Please refer to the gem's documentation to do it accordingly.

You would also want to update the DAVINCI_MAX_TOKENS constant to 4096 

```
The maximum number of tokens allowed for the generated answer. By default, the number of tokens the model can return will be (4096 - prompt tokens).
```

**Comment by Huiclaire** [comment]
Hi @silva96, nice to meet you! I would love to take on this task. I'm still a beginner, but I'm excited to learn more about Turbo. It may take me a bit of time, is that okay?

**Comment by heyextra** [comment]
I would also love to take a crack at this.

**Comment by JuzerShakir** [comment]
Hey there, thanks for giving us the opportunity to learn and grow. 😄 I wanted to let you know that I am currently working on this issue because as I see no one has been assigned yet.

**Comment by silva96** [comment]
Hey, @heyextra @JuzerShakir @Huiclaire here's the thing: I went to sleep and I got 3 offers from you three, but @JuzerShakir started right away.

As @Huiclaire requested the issue first, I'll give her the opportunity to take this issue and pay the bounty if the result is OK.
But also, as @JuzerShakir already opened a PR, I'll give him the chance to correct it and see how it works.

I'll keep the best result of both, but will pay both if both PR's are good.

@JuzerShakir for the next time, don't start a PR if I didn't assigned you to work on it. In this case, @Huiclaire asked first so I'd have assigned to her.

Thanks all!

@Huiclaire let me know if you are ok to start.

**Comment by JuzerShakir** [comment]
Sorry 🙏 @silva96 ,really sorry! I am new to this and I let my excitement carry me away. I have understood and I won't repeat that again!

**Comment by silva96** [comment]
Thanks everyone, the task is done, I just accepted @JuzerShakir PR because @Huiclaire didn't submit or respond anything.

**Comment by Huiclaire** [comment]
Hi @silva96 , sorry for the late reply. I'm in Taiwan so the time difference may have caused the inconvenience. But thank you for assigning it to me,  and I hope we can have the opportunity to work together in the future!
